[package]
name = "subtitle-translator-cli"
version = "0.1.0"
edition = "2021"
authors = ["Chen Tao<chentao020717Work@outlook.com>"]
license = "MIT"
description = "A tool to translate subtitle files"
readme = "README.md"
homepage = "https://github.com/eeee0717/subtitle-translator-cli"
repository = "https://github.com/eeee0717/subtitle-translator-cli"
keywords = ["cli", "subtitle", "translator"]
categories = ["command-line-utilities"]

[[bin]]
name = "stc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rustlate = "1.0.0"
regex = "1.10.5"
rayon = "1.10.0"
indicatif = "0.17.8"
glob = "0.3.1"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
async-openai = "0.23.4"
serde_json = "1.0.121"
